
homeassistant:
  name: #homeassistant name
  unit_system: metric
  time_zone: Europe/Madrid
  customize: !include customize.yaml

#introduction:
discovery:
device_tracker:
conversation:
history:
logbook:
map:
sun:
smartir:
config:
stream:
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
wake_on_lan:
system_health:
frontend:
  themes: !include themes.yaml

recorder: #This only keeps 1 days log for entity state history
  purge_keep_days: 1

weather:
  - platform: darksky
    api_key: #apikey


ios:
  push:
    categories:
      - name: cameras
        identifier: 'camera'
        actions:
          - identifier: 'TTS_MESSAGE'
            title: 'Alexa TTS Message'
            behavior: 'textInput'
            textInputButtonTitle: 'Send TTS'
            textInputPlaceholder: 'What do you want to say?'


cloud:
  alexa:
    filter:
      include_entities:
      - switch.garage_light
      - switch.studio_wall_lights
      - switch.studio_stairs


alexa_media:
  accounts:
    - email: email@email.com
      password: !secret amazon_password
      url: amazon.es


binary_sensor:
  - platform: mqtt
    name: Garage Door
    state_topic: "stat/garagedoord1mini/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    device_class: garage_door
    qos: 1
  - platform: mqtt
    name: Hall PIR
    state_topic: "home/bridge/recieve"
    payload_on: "hallpir"
    payload_off: "hallpiroff"
    device_class: motion
    qos: 1
  - platform: mqtt
    name: Studio Door
    state_topic: "home/bridge2/recieve"
    payload_on: "sd1"
    payload_off: "sd0"
    device_class: door
    qos: 1


speedtestdotnet:
  scan_interval:
    minutes: 60
  monitored_conditions:
    - ping
    - download
    - upload
  server_id: 7353


input_boolean:
  master_bedroom_light:
    name: Bedroom Light

input_text:
  alexa_tts:
    name: Alexa, Say...
#    initial: Hi
    icon: mdi:amazon-alexa

input_select:
  guest_room_fan:
    name: Guest Room Fan
    options:
     - Low
     - Medium
     - High
     - Off
#    initial: Off
    icon: mdi:fan


switch:
  - platform: mqtt
    name: "Garage Light"
    command_topic: "cmnd/garagelight/power"
    state_topic: "stat/garagelight/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    icon: mdi:lightbulb
  - platform: broadlink
    host: 192.168.18.191
    mac: 'c8:f7:42:16:a7:e0'
    friendly_name: "Bedroom Blackbean"
    timeout: 15
    switches:
      notused_power:
        friendly_name: "Notusedpower"
        command_on: 'JgBQAAABKZMTEhMSFBEUERQSExITEhMSEzcTEhM2FDYTNxM3TEhQSExITEhMSExITEhQ2EzcTNhQ2EzcTNhQ2FAAFbQABKkgUAAAAAAA='



climate:
  - platform: smartir
    name: Studio AirCon
    unique_id: studio_aircon
    device_code: 1320
    controller_data: 192.168.18.134
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.ac_power

media_player:
  - platform: webostv
    host: 192.168.18.6
    name: Bedroom TV
    filename: webostv.conf
    timeout: 5
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: "3c-cd-93-03-b3-61"

cover:
  - platform: template
    covers:
      garage_door:
        friendly_name: "Garage Door"
        value_template: "{{ is_state('binary_sensor.garage_door', 'on') }}"
        open_cover:
          service: switch.turn_on
          data:
            entity_id: switch.open_garage
        close_cover:
          service: switch.turn_on
          data:
            entity_id: switch.close_garage
        # stop_cover:
        #   service: switch.turn_on
        #   data:
        #     entity_id: switch.garage_door
        icon_template: >-
          {% if states('binary_sensor.garage_door')|float > 0 %}
            mdi:garage-open
          {% else %}
            mdi:garage
          {% endif %}

camera:
  - platform: generic
    name: Garage
    still_image_url: "http://192.168.18.10/cgi-bin/api.cgi?cmd=Snap&amp;channel=0&amp;rs=wuuPhkmUCeI9WG7C&amp;user=wayne&amp;password=2809wpcmj0902"
    stream_source: "rtsp://wayne:2809wpcmj0902@192.168.18.10:554/h264Preview_01_main"
