
#binary_sensor:

### PIR Motion Sensors ###

  - platform: mqtt
    state_topic: "hall/pir"
    payload_on: "1"
    payload_off: "0"
    name: "Downstairs Hall"
    device_class: motion
  - platform: mqtt
    state_topic: "livingroommultisensor/pir"
    payload_on: "1"
    payload_off: "0"
    name: "Living Room"
    device_class: motion
  - platform: mqtt
    state_topic: "landing/pir"
    payload_on: "1"
    payload_off: "0"
    name: "Landing"
    device_class: motion
  - platform: mqtt
    state_topic: "lock/pir"
    payload_on: "1"
    payload_off: "0"
    name: "Garage"
    device_class: motion
  - platform: mqtt
    state_topic: "charliesmultisensor/pir"
    payload_on: "1"
    payload_off: "0"
    name: "Charlies Room"
    device_class: motion
  - platform: mqtt
    state_topic: "liasmultisensor/pir"
    payload_on: "1"
    payload_off: "0"
    name: "Lias Room"
    device_class: motion
  - platform: mqtt
    state_topic: "kitchenmultisensor/pir"
    payload_on: "1"
    payload_off: "0"
    name: "Kitchen"
    device_class: motion
  - platform: mqtt
    state_topic: "bedroommultisensor/pir"
    payload_on: "1"
    payload_off: "0"
    name: "Bedroom"
    device_class: motion
  - platform: mqtt
    state_topic: "kidsbathroomsensor/pir"
    payload_on: "1"
    payload_off: "0"
    name: "Kids Bathroom"
    device_class: motion


### 433 Motion Sensors ###

  - platform: mqtt
    name: "Garage 2"
    state_topic: "tele/sonoffrf/RESULT"
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: "5C0914"
    payload_off: "OFF"
    device_class: motion
    off_delay: 3
    qos: 1
  - platform: mqtt
    name: "Front Yard"
    state_topic: "tele/sonoffrf/RESULT"
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: "EC2EEE"
    payload_off: "OFF"
    off_delay: 3
    device_class: motion
    qos: 1
  - platform: mqtt
    name: "Toilet"
    state_topic: "tele/sonoffrf/RESULT"
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: "EF553E"
    payload_off: "OFF"
    off_delay: 3
    device_class: motion
    qos: 1


### 433 Door Sensors ###

  - platform: mqtt
    name: "Garage Stairs Door"
    state_topic: "tele/sonoffrf/RESULT"
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: "18290A"
    payload_off: "18290E"
    device_class: door
    qos: 1
  - platform: mqtt
    name: "Front Door"
    state_topic: "tele/sonoffrf/RESULT"
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: "14AB0A"
    payload_off: "14AB0E"
    device_class: door
    qos: 1


### Alarm Sensors ###

  - platform: mqtt
    state_topic: "tele/sonoffrf/RESULT"
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: "7C6C64"
    payload_off: "OFF"
    off_delay: 3
    name: "Smoke Alarm"
    device_class: smoke
  - platform: mqtt
    state_topic: "tele/sonoffrf/RESULT"
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: "88678C"
    payload_off: "OFF"
    off_delay: 3
    name: "Gas Alarm"
    device_class: smoke


### Ping Sensors ###

  - platform: ping
    name: Ping PC
    host: !secret radarr_ip
    count: 3
  - platform: ping
    name: Ping Plex
    host: !secret plex_ip
    count: 3
  - platform: ping
    name: Ping Mac
    host: !secret mac_ip
    count: 3
















