homeassistant:
  customize: !include customize.yaml
  media_dirs:
    recordings: /media/cameras/Recordings
    snapshots: /media/cameras/Snapshots

shell_command:
  purge_cctv_recordings: find /media/cameras/Recordings/ -maxdepth 2 -type f -mtime +2 -exec rm {} -f \;
  purge_cctv_snapshots: find /media/cameras/Snapshots/ -maxdepth 2 -type f -mtime +2 -exec rm {} -f \;

frontend:
  themes: !include_dir_merge_named themes

default_config:
config:
conversation:
history:
logbook:
map:
sun:
smartir:
system_health:
wake_on_lan:
stream:
ffmpeg:
momentary:
mobile_app:
glances:
http:
updater:
python_script:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
light: !include lights.yaml
switch: !include switches.yaml

notify:
  - platform: alexa_media
    name: alexa_media

recorder:
  purge_keep_days: 3

weather:
  - platform: darksky
    api_key: !secret darksky_api
    mode: daily

tts:
  - platform: google_translate
    service_name: google_say

transmission:
  name: Radarr
  host: !secret radarr_transmission_ip

cloud:
  alexa:
    entity_config:
      light.desk_lamp:
        display_categories: SWITCH
      light.bedroom_hall:
        display_categories: SWITCH
      light.salt_lamp:
        display_categories: SWITCH
      cover.left_blind:
        display_categories: INTERIOR_BLIND
      cover.right_blind:
        display_categories: INTERIOR_BLIND
    filter:
      include_domains:
      - light
      - climate
      - lock
      - cover
      exclude_entities:
      - light.hallcam_light
      - light.spycam_light
      - light.garage_wall_switch
      include_entities:
      - switch.bedroom_tv
      - switch.workbench_light
      - switch.lamp

      - media_player.charlies_tv
      - media_player.lias_tv
      - media_player.tv

      - script.charlies_tv_plex
      - script.charlies_tv_youtube
      - script.lias_tv_plex
      - script.lias_tv_youtube
      - script.livingroom_tv_plex
      - script.livingroom_tv_netflix
      - script.livingroom_hdmi1
      - script.livingroom_hdmi2
      - script.livingroom_hdmi3
      - script.livingroom_mag_bbc1
      - script.livingroom_mag_bbc2
      - script.livingroom_mag_itv1
      - script.livingroom_mag_itv2
      - script.livingroom_mag_e4
      - script.livingroom_mag_itvbe
      - script.livingroom_mag_cartoon_network
      - script.livingroom_mag_e
      - script.stop_the_blinds
      - script.bedtime_routine

      - binary_sensor.front_door
      - binary_sensor.garage_door
      - binary_sensor.garage_stairs_door

      - sensor.kitchen_temperature
      - sensor.outside_temperature
      - sensor.garage_temperature

homekit:
#  pincode: 123-45-678
  filter:
    include_domains:
      - light
      - climate
    exclude_entities:
      - light.hallcam_light
      - light.spycam_light

ios:
  push:
    categories:
    #   - name: cameras
    #     identifier: 'camera'
    #     actions:
    #       - identifier: 'TTS_MESSAGE'
    #         title: 'Alexa TTS Message'
    #         behavior: 'textInput'
    #         textInputButtonTitle: 'Send TTS'
    #         textInputPlaceholder: 'What do you want to say?'
      - name: Alarm
        identifier: 'alarm'
        actions:
          - identifier: 'RESET_ALARM'
            title: 'Reset Alarm'
      - name: PC
        identifier: 'pc'
        actions:
          - identifier: 'PC_REBOOT'
            title: 'Reboot PC'
    

speedtestdotnet:
  scan_interval:
    minutes: 60
  monitored_conditions:
    - ping
    - download
    - upload
  server_id: !secret speedtest_server_id

webostv:
  - host: !secret charlies_tv_ip
    name: Charlies TV
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret charlies_tv_mac
  - host: !secret lias_tv_ip
    name: Lias TV
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret lias_tv_mac
  - host: !secret livingroom_tv_ip
    name: TV
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret livingroom_tv_mac

zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 100
    icon: mdi:home

input_select:
  alexa:
    name: Alexa Device
    options:
      - Kitchen
      - Living Room
      - Bedroom
      - Lias Room
      - Charlies Room
      - Garage
      - Downstairs
      - Upstairs
      - All
      - None
    icon: mdi:amazon-alexa
    initial: None

input_boolean:
  lamp_lux:
  bedroom_light:
    name: Bedroom Light

input_text:
  alexa_tts:
    name: Alexa, Say...
    initial: ''
    icon: mdi:amazon-alexa

input_number:
  peak_price:
    name: Peak price per Kwh
    unit_of_measurement: €
    min: 0.001
    max: 0.200
    step: 0.001
    mode: box
  offpeak_price:
    name: Off-Peak price per Kwh
    unit_of_measurement: €
    min: 0.001
    max: 0.100
    step: 0.001
    mode: box
  energy_cost_last_month:
    min: 0.01
    max: 200.00
    step: 0.01
    mode: box

alarm_control_panel:
  - platform: manual
    name: Alarm
    code: !secret alarm_code
    arming_time: 30
    delay_time: 20
    trigger_time: 300
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0

lock:
  - platform: template
    name: Garage door
    value_template: "{{ is_state('switch.garage_door_lock', 'on') }}"
    lock:
      service: switch.turn_on
      data:
        entity_id: switch.garage_door_lock
    unlock:
      service: switch.turn_off
      data:
        entity_id: switch.garage_door_lock

climate:
  - platform: smartir
    name: Livingroom Aircon
    unique_id: livingroom_ac
    device_code: 1001
    controller_data: remote.living_room_remote
    temperature_sensor: sensor.living_room_temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.ac_power
  - platform: smartir
    name: Bedroom Aircon
    unique_id: bedroom_ac
    device_code: 10012
    controller_data: remote.bedroom_remote
    temperature_sensor: sensor.bedroom_temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.ac_power
  - platform: smartir
    name: Charlies Aircon
    unique_id: charlies_ac
    device_code: 1001
    controller_data: remote.charlies_remote
    temperature_sensor: sensor.charlies_room_temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.ac_power
  - platform: smartir
    name: Lias Aircon
    unique_id: lias_ac
    device_code: 1001
    controller_data: remote.lias_remote
    temperature_sensor: sensor.lias_room_temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.ac_power

utility_meter:
  home_energy_meter_monthly:
    source: sensor.shelly_em_energy
    cycle: monthly
    offset:
      days: 5
    tariffs:
      - peak
      - offpeak
  home_energy_meter_weekly:
    source: sensor.shelly_em_energy
    cycle: weekly
    tariffs:
      - peak
      - offpeak
  home_energy_meter_daily:
    source: sensor.shelly_em_energy
    cycle: daily
    tariffs:
      - peak
      - offpeak

camera:
  - platform: generic
    name: Garage Camera
    still_image_url: !secret garage_camera_still_image_url
    stream_source: !secret garage_camera_stream_source
  - platform: generic
    name: Front Yard Camera
    still_image_url: !secret front_yard_camera_still_image_url
    stream_source: !secret front_yard_stream_source
  - platform: generic
    name: Hall Camera
    still_image_url: !secret hall_camera_still_image_url
    stream_source: !secret hall_camera_stream_source
  - platform: generic
    name: Workbench Camera
    still_image_url: !secret workbench_camera_still_image_url
    stream_source: !secret workbench_camera_stream_source

