
#switch:

### Tasmota Switches ###

  - platform: mqtt
    name: "Living Room Mozzie Plug"
    command_topic: "cmnd/livingroommozzieplug/power"
    state_topic: "stat/livingroommozzieplug/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    icon: mdi:power-socket-eu
  - platform: mqtt
    name: "Bedroom Mozzie Plug"
    state_topic: "stat/bedroommozzieplug/POWER"
    command_topic: "cmnd/bedroommozzieplug/power"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    icon: mdi:power-socket-eu
  - platform: mqtt
    name: "Garage Door Lock"
    command_topic: "cmnd/magneticlock/power"
    state_topic: "stat/magneticlock/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    icon: mdi:lock
  - platform: mqtt
    name: "Boiler Plug"
    command_topic: "cmnd/boilerplug/power"
    state_topic: "stat/boilerplug/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    icon: mdi:power-socket-eu
  - platform: mqtt
    name: "Washing Machine Plug"
    command_topic: "cmnd/washingmachine/power"
    state_topic: "stat/washingmachine/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    icon: mdi:power-socket-eu
  - platform: mqtt
    name: "Dishwasher Plug"
    command_topic: "cmnd/dishwasherplug/power"
    state_topic: "stat/dishwasherplug/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    icon: mdi:power-socket-eu



### Shelly Switches ###

  - platform: mqtt
    name: "Tumble Dryer Plug"
    state_topic: "shellies/shellyplug-s-50DADA/relay/0"
    command_topic: "shellies/shellyplug-s-50DADA/relay/0/command"
    qos: 1
    payload_on: "on"
    payload_off: "off"
    icon: mdi:power-socket-eu



### Garage Door Switches ###

  - platform: mqtt
    name: "Open"
    command_topic: "cmnd/garage/power1"
    state_topic: "stat/garage/POWER1"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    icon: mdi:garage
  - platform: mqtt
    name: "Close"
    command_topic: "cmnd/garage/power2"
    state_topic: "stat/garage/POWER2"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    icon: mdi:garage



### Broadlink RM Mini Switches ###

  - platform: broadlink
    mac: !secret bedroom_broadlink_mac
    switches:
      - name: Bedroom TV
        command_on: 'JgBwAE4VExQnFCcUJxUTFCcUExUnFBMUFBQTFBMAAz5OFBQUJxQnFCcUFBQnFBMVJxQTFBMVExQTAAM+ThQUFCcUJxQnFBQUJxQTFCcVExQTFBQUEwADPk4UFBQnFCcUJxQTFScUExQnFBQUExQUFBMADQUAAAAAAAAAAA=='
        command_off: 'JgCoAE8UJxQnFCcVJhUTFCcUFBQnFBMUFBQTFBQAAylPFCcUJxQnFCcVExQnFBMVJxQTFBQUExQTAAMrTRUnFCcUJxQnFBQUJxQTFSYVExQTFRMUEwADK00VJxQnFCcUJxQUFCcUExQnFRMUExUTFBMAAypOFSYVJxQnFCcUExUnFBMUJxUTFBMUFBQTAAMqThQnFScUJxQnFBMVJxQTFCcUFBQTFBQUEwANBQ=='



### Momentary Switches ###

  - platform: momentary
    name: Hallcam Record
    mode: on
    toggle_for: 1
    cancellable: False
  - platform: momentary
    name: Hallcam Snapshot
    mode: on
    toggle_for: 1
    cancellable: False
  - platform: momentary
    name: Garagecam Record
    mode: on
    toggle_for: 1
    cancellable: False
  - platform: momentary
    name: Garagecam Snapshot
    mode: on
    toggle_for: 1
    cancellable: False
  - platform: momentary
    name: Workbenchcam Record
    mode: on
    toggle_for: 1
    cancellable: False
  - platform: momentary
    name: Workbenchcam Snapshot
    mode: on
    toggle_for: 1
    cancellable: False
  - platform: momentary
    name: Frontyardcam Record
    mode: on
    toggle_for: 1
    cancellable: False
  - platform: momentary
    name: Frontyardcam Snapshot
    mode: on
    toggle_for: 1
    cancellable: False





















